version: '{build}'

image:
  - Visual Studio 2015

platform:
- x64

environment:
  os_name: windows
  tf_type: cpu
  tf_tag_name: r1.6
  tf_version: 1.6.0

  matrix:
    - vcvar_arg: x86
      platform_name: x86
      cmake_ext_arg: ""
    - vcvar_arg: amd64
      platform_name: x86_64
      cmake_ext_arg: " -A x64"

install:
  - cmd: git clone https://github.com/tensorflow/tensorflow
  - cmd: cd tensorflow && git checkout %tf_tag_name%
  - if [%platform_name%]==[x86] git apply ../patches/32bit.patch
  - cmd: git apply ../patches/add-ops.patch
  - cmd: mkdir c:\tf && cd c:\tf
  - cmd: vcpkg integrate remove

build_script:
  - cmd: cmake C:\projects\build-tensorflow\tensorflow\tensorflow\contrib\cmake -DCMAKE_BUILD_TYPE=Release %cmake_ext_arg% -Dtensorflow_BUILD_CC_EXAMPLE=OFF -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF -Dtensorflow_BUILD_SHARED_LIB=ON -Dtensorflow_BUILD_CONTRIB_KERNELS=OFF -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=OFF -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF -Dtensorflow_BUILD_ALL_KERNELS=OFF
  - cmd: MSBuild /m /p:Configuration=Release tensorflow.vcxproj

after_build:
  - cmd: 7z a C:\projects\build-tensorflow\libtensorflow-%tf_type%-%os_name%-%platform_name%-%tf_version%.zip C:\tf\Release\tensorflow.dll C:\tf\Release\tensorflow.lib

artifacts:
  - path: libtensorflow-%tf_type%-%os_name%-%platform_name%-%tf_version%.zip
    name: libtensorflow-%tf_type%-%os_name%-%platform_name%-%tf_version%.zip

deploy:
  release: TensorFlow-$(tf_version)
  description: 'Prebuilded 32 bit (x86) and 64 bit (x86-64) cpu version of TensorFlow C and C++ API for Windows and Linux'
  provider: GitHub
  auth_token:
    secure: 0BKAHbP+Qv2LWfj/sM7t00NAutlp3CJJpQp41RphbkIBRg/QRK7YXIchLHivLxWS
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
